version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/share/nginx/html
    depends_on:
      - api
    networks:
      - memo-network

  api:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    command: >
      sh -c "npm install -g json-server && 
             json-server --watch /app/data/db.json --host 0.0.0.0 --port 3000"
    networks:
      - memo-network

networks:
  memo-network:
    driver: bridge